approvals:
  # PR needs at least 2 approvals
  minimum: 2
  # approval = comment that matches this regex
  pattern: "^(:\\+1:|👍)$"
  from:
    # commenter must be either one of:
    # a public lambdastack org member
    orgs:
      - lambdastack
    # a collaborator of the repo
    collaborators: true
